export const Shipments = [
    {
      dateExpected: 'Thu Nov 03 2022',
      dateDelivered: 'n/a',
      dateShipped: 'Thu Sep 15 2022',
      shipmentID: '1',
      driverID: '1',
      origin: 'Arizona',
      destination: 'Pennsylvania',
      dangerFlag: false,
      currentLocation: 'Pennsylvania',
      stops: [ 'Anchorage', 'Pittsburgh', 'Pennsylvania', 'Pennsylvania' ]
    },
    {
      dateExpected: 'Sat Apr 08 2023',
      dateDelivered: 'n/a',
      dateShipped: 'Thu Feb 23 2023',
      shipmentID: '2',
      driverID: '2',
      origin: 'Philadelphia',
      destination: 'Texas',
      dangerFlag: true,
      currentLocation: 'Greensboro',
      stops: [ 'El Paso', 'Cincinnati', 'North Carolina', 'Greensboro' ]
    },
    {
      dateExpected: 'Thu Jun 01 2023',
      dateDelivered: 'Wed May 31 2023',
      dateShipped: 'Thu May 11 2023',
      shipmentID: '3',
      driverID: '3',
      origin: 'Anchorage',
      destination: 'Garland',
      dangerFlag: true,
      currentLocation: 'Garland',
      stops: [ 'Texas', 'Kansas', 'Kansas', 'Garland' ]
    },
    {
      dateExpected: 'Sun Aug 20 2023',
      dateDelivered: 'n/a',
      dateShipped: 'Sun Jul 09 2023',
      shipmentID: '4',
      driverID: '4',
      origin: 'Arizona',
      destination: 'New Orleans',
      dangerFlag: false,
      currentLocation: 'Oklahoma',
      stops: [ 'Chandler', 'Arizona', 'Oklahoma' ]
    },
    {
      dateExpected: 'Sat May 13 2023',
      dateDelivered: 'Wed May 10 2023',
      dateShipped: 'Fri Mar 24 2023',
      shipmentID: '5',
      driverID: '5',
      origin: 'Tennessee',
      destination: 'Henderson',
      dangerFlag: false,
      currentLocation: 'Henderson',
      stops: [ 'Indianapolis', 'Nevada', 'Indiana', 'Henderson' ]
    },
    {
      dateExpected: 'Thu Mar 23 2023',
      dateDelivered: 'n/a',
      dateShipped: 'Mon Mar 06 2023',
      shipmentID: '6',
      driverID: '1',
      origin: 'Pennsylvania',
      destination: 'Lubbock',
      dangerFlag: true,
      currentLocation: 'Alaska',
      stops: [ 'Fort Wayne', 'Pennsylvania', 'Alaska' ]
    },
    {
      dateExpected: 'Fri Jun 03 2022',
      dateDelivered: 'n/a',
      dateShipped: 'Tue May 24 2022',
      shipmentID: '7',
      driverID: '2',
      origin: 'North Carolina',
      destination: 'Wichita',
      dangerFlag: false,
      currentLocation: 'Indiana',
      stops: [ 'Oklahoma City', 'Indiana' ]
    },
    {
      dateExpected: 'Mon Mar 20 2023',
      dateDelivered: 'Sun Mar 19 2023',
      dateShipped: 'Fri Feb 03 2023',
      shipmentID: '8',
      driverID: '3',
      origin: 'Pittsburgh',
      destination: 'Cincinnati',
      dangerFlag: true,
      currentLocation: 'Cincinnati',
      stops: [ 'North Carolina', 'Oklahoma', 'North Carolina', 'Cincinnati' ]
    },
    {
      dateExpected: 'Fri Nov 10 2023',
      dateDelivered: 'Tue Nov 07 2023',
      dateShipped: 'Fri Sep 22 2023',
      shipmentID: '9',
      driverID: '4',
      origin: 'Fort Wayne',
      destination: 'Arizona',
      dangerFlag: false,
      currentLocation: 'Arizona',
      stops: [ 'New York', 'Arizona' ]
    },
    {
      dateExpected: 'Tue Jul 11 2023',
      dateDelivered: 'n/a',
      dateShipped: 'Wed Jun 07 2023',
      shipmentID: '10',
      driverID: '5',
      origin: 'North Carolina',
      destination: 'Philadelphia',
      dangerFlag: false,
      currentLocation: 'New York',
      stops: [ 'Nevada', 'Arizona', 'New York' ]
    }
];