export const Shipments = [
  {
    dateExpected: 'Thu Sep 22 2022',
    dateDelivered: 'Wed Sep 21 2022',
    dateShipped: 'Sat Sep 03 2022',
    shipmentID: '1',
    driverID: '1',
    origin: 'Alaska',
    destination: 'Kentucky',
    currentLocation: 'Kentucky',
    stops: [ 'Philadelphia', 'Kentucky' ],
    packages:[
      {dangerFlag:"Passed",origin:"Pennsylvania",destination:"Kentucky",shipmentID:"1",id:"1",currentLocation:"Kentucky",price:159503,content:"Candy",size:"96cm x 26cm x 50cm",weight:"4kg"},
      {dangerFlag:"Failed",origin:"Lexington",destination:"Kentucky",shipmentID:"1",id:"2",currentLocation:"Kentucky",price:27058,content:"Clothing",size:"61cm x 42cm x 101cm",weight:"6kg"},
      {dangerFlag:"Failed",origin:"Henderson",destination:"Kentucky",shipmentID:"1",id:"3",currentLocation:"Kentucky",price:488631,content:"Kitchen Utensils",size:"59cm x 103cm x 68cm",weight:"30kg"},
      {dangerFlag:"Inspect",origin:"Memphis",destination:"Kentucky",shipmentID:"1",id:"4",currentLocation:"Kentucky",price:409389,content:"Kitchen Utensils",size:"64cm x 58cm x 51cm",weight:"46kg"},
      {dangerFlag:"Failed",origin:"Nevada",destination:"Kentucky",shipmentID:"1",id:"5",currentLocation:"Kentucky",price:33689,content:"Machinery",size:"27cm x 24cm x 31cm",weight:"25kg"},
      {dangerFlag:"Passed",origin:"Pittsburgh",destination:"Kentucky",shipmentID:"1",id:"6",currentLocation:"Kentucky",price:240191,content:"Metal",size:"15cm x 96cm x 106cm",weight:"10kg"},
      {dangerFlag:"Failed",origin:"Arizona",destination:"Kentucky",shipmentID:"1",id:"7",currentLocation:"Kentucky",price:254872,content:"Metal",size:"97cm x 58cm x 63cm",weight:"46kg"},
      {dangerFlag:"Passed",origin:"Reno",destination:"Kentucky",shipmentID:"1",id:"8",currentLocation:"Kentucky",price:129245,content:"Chemicals",size:"27cm x 63cm x 15cm",weight:"12kg"},
      {dangerFlag:"Inspect",origin:"Fort Wayne",destination:"Kentucky",shipmentID:"1",id:"9",currentLocation:"Kentucky",price:407938,content:"Weaves",size:"67cm x 50cm x 68cm",weight:"13kg"},
      {dangerFlag:"Inspect",origin:"New York",destination:"Kentucky",shipmentID:"1",id:"10",currentLocation:"Kentucky",price:441278,content:"Rubber",size:"87cm x 51cm x 62cm",weight:"42kg"},

    ]
  },
  {
    dateExpected: 'Mon Aug 28 2023',
    dateDelivered: 'Fri Aug 25 2023',
    dateShipped: 'Thu Jul 06 2023',
    shipmentID: '2',
    driverID: '2',
    origin: 'North Carolina',
    destination: 'Buffalo',
    currentLocation: 'Buffalo',
    stops: [ 'Pennsylvania', 'Kentucky', 'Buffalo' ],
    packages: [
      {dangerFlag:"Inspect",origin:"Lexington",destination:"Buffalo",shipmentID:"2",id:"11",currentLocation:"Buffalo",price:72972,content:"Garden Tools",size:"94cm x 39cm x 98cm",weight:"34kg"},
      {dangerFlag:"Inspect",origin:"New York",destination:"Buffalo",shipmentID:"2",id:"12",currentLocation:"Buffalo",price:472801,content:"Weaves",size:"75cm x 64cm x 31cm",weight:"6kg"},
      {dangerFlag:"Failed",origin:"Reno",destination:"Buffalo",shipmentID:"2",id:"14",currentLocation:"Buffalo",price:33471,content:"Machinery",size:"13cm x 26cm x 100cm",weight:"27kg"},
      {dangerFlag:"Failed",origin:"Greensboro",destination:"Buffalo",shipmentID:"2",id:"13",currentLocation:"Buffalo",price:232860,content:"Cleaning Products",size:"103cm x 58cm x 53cm",weight:"46kg"},
      {dangerFlag:"Inspect",origin:"Fort Wayne",destination:"Buffalo",shipmentID:"2",id:"15",currentLocation:"Buffalo",price:246185,content:"Bread",size:"21cm x 107cm x 45cm",weight:"10kg"},
      {dangerFlag:"Inspect",origin:"Kentucky",destination:"Buffalo",shipmentID:"2",id:"16",currentLocation:"Buffalo",price:178528,content:"Cleaning Products",size:"50cm x 28cm x 91cm",weight:"31kg"},
      {dangerFlag:"Failed",origin:"Chandler",destination:"Buffalo",shipmentID:"2",id:"17",currentLocation:"Buffalo",price:119943,content:"Bread",size:"106cm x 37cm x 31cm",weight:"14kg"},
      {dangerFlag:"Failed",origin:"Texas",destination:"Buffalo",shipmentID:"2",id:"18",currentLocation:"Buffalo",price:308939,content:"Coffee",size:"75cm x 94cm x 37cm",weight:"13kg"},
      {dangerFlag:"Passed",origin:"Oklahoma City",destination:"Buffalo",shipmentID:"2",id:"19",currentLocation:"Buffalo",price:279371,content:"Candy",size:"96cm x 90cm x 102cm",weight:"5kg"},
      {dangerFlag:"Passed",origin:"Cincinnati",destination:"Buffalo",shipmentID:"2",id:"20",currentLocation:"Buffalo",price:105724,content:"Oranges",size:"85cm x 32cm x 61cm",weight:"15kg"},
    ]
  },
  {
    dateExpected: 'Tue Dec 19 2023',
    dateDelivered: 'Sun Dec 17 2023',
    dateShipped: 'Wed Nov 01 2023',
    shipmentID: '3',
    driverID: '3',
    origin: 'Garland',
    destination: 'Greensboro',
    currentLocation: 'Greensboro',
    stops: [ 'Garland', 'Memphis', 'Wichita', 'Greensboro' ],
    packages: [
      {dangerFlag:"Failed",origin:"Pittsburgh",destination:"Greensboro",shipmentID:"3",id:"21",currentLocation:"Greensboro",price:451812,content:"Candy",size:"99cm x 16cm x 14cm",weight:"30kg"},
      {dangerFlag:"Failed",origin:"Pittsburgh",destination:"Greensboro",shipmentID:"3",id:"23",currentLocation:"Greensboro",price:461189,content:"Clothing",size:"49cm x 81cm x 101cm",weight:"27kg"},
      {dangerFlag:"Passed",origin:"Pittsburgh",destination:"Greensboro",shipmentID:"3",id:"22",currentLocation:"Greensboro",price:125586,content:"Machinery",size:"70cm x 37cm x 96cm",weight:"40kg"},
      {dangerFlag:"Inspect",origin:"North Carolina",destination:"Greensboro",shipmentID:"3",id:"25",currentLocation:"Greensboro",price:322024,content:"Candy",size:"27cm x 14cm x 91cm",weight:"25kg"},
      {dangerFlag:"Passed",origin:"Henderson",destination:"Greensboro",shipmentID:"3",id:"26",currentLocation:"Greensboro",price:161884,content:"Game Console",size:"53cm x 67cm x 12cm",weight:"42kg"},
      {dangerFlag:"Passed",origin:"Pennsylvania",destination:"Greensboro",shipmentID:"3",id:"24",currentLocation:"Greensboro",price:102686,content:"Machinery",size:"40cm x 71cm x 40cm",weight:"7kg"},
      {dangerFlag:"Passed",origin:"El Paso",destination:"Greensboro",shipmentID:"3",id:"27",currentLocation:"Greensboro",price:383069,content:"Bread",size:"83cm x 13cm x 26cm",weight:"33kg"},
      {dangerFlag:"Failed",origin:"Pennsylvania",destination:"Greensboro",shipmentID:"3",id:"28",currentLocation:"Greensboro",price:174151,content:"Game Console",size:"60cm x 98cm x 85cm",weight:"49kg"},
      {dangerFlag:"Failed",origin:"Chandler",destination:"Greensboro",shipmentID:"3",id:"29",currentLocation:"Greensboro",price:440885,content:"Chemicals",size:"78cm x 62cm x 71cm",weight:"7kg"},
      {dangerFlag:"Failed",origin:"Cincinnati",destination:"Greensboro",shipmentID:"3",id:"30",currentLocation:"Greensboro",price:200197,content:"Metal",size:"21cm x 100cm x 10cm",weight:"13kg"},
    ]
  },
  {
    dateExpected: 'Fri Oct 14 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Sat Aug 20 2022',
    shipmentID: '4',
    driverID: '4',
    origin: 'Kentucky',
    destination: 'Buffalo',
    currentLocation: 'Alaska',
    stops: [ 'Greensboro', 'Oklahoma City', 'Tennessee', 'Alaska' ],
    packages: [
      {dangerFlag:"Passed",origin:"Indianapolis",destination:"Buffalo",shipmentID:"4",id:"31",currentLocation:"Alaska",price:147131,content:"Medicine",size:"102cm x 73cm x 14cm",weight:"43kg"},
      {dangerFlag:"Inspect",origin:"Pennsylvania",destination:"Buffalo",shipmentID:"4",id:"32",currentLocation:"Alaska",price:425924,content:"Kitchen Utensils",size:"91cm x 67cm x 63cm",weight:"43kg"},
      {dangerFlag:"Failed",origin:"Pennsylvania",destination:"Buffalo",shipmentID:"4",id:"33",currentLocation:"Alaska",price:432856,content:"Kitchen Utensils",size:"57cm x 58cm x 101cm",weight:"32kg"},
      {dangerFlag:"Failed",origin:"Fayette",destination:"Buffalo",shipmentID:"4",id:"34",currentLocation:"Alaska",price:201355,content:"Weaves",size:"21cm x 21cm x 12cm",weight:"42kg"},
      {dangerFlag:"Inspect",origin:"Fort Wayne",destination:"Buffalo",shipmentID:"4",id:"35",currentLocation:"Alaska",price:165607,content:"Game Console",size:"66cm x 72cm x 46cm",weight:"45kg"},
      {dangerFlag:"Passed",origin:"Tennessee",destination:"Buffalo",shipmentID:"4",id:"36",currentLocation:"Alaska",price:380816,content:"Weaves",size:"79cm x 27cm x 101cm",weight:"18kg"},
      {dangerFlag:"Passed",origin:"Kentucky",destination:"Buffalo",shipmentID:"4",id:"37",currentLocation:"Alaska",price:293207,content:"Metal",size:"76cm x 28cm x 26cm",weight:"1kg"},
      {dangerFlag:"Passed",origin:"Cincinnati",destination:"Buffalo",shipmentID:"4",id:"38",currentLocation:"Alaska",price:410369,content:"Bath Products",size:"36cm x 17cm x 56cm",weight:"27kg"},
      {dangerFlag:"Failed",origin:"Oklahoma",destination:"Buffalo",shipmentID:"4",id:"39",currentLocation:"Alaska",price:288689,content:"Machinery",size:"53cm x 21cm x 101cm",weight:"25kg"},
      {dangerFlag:"Failed",origin:"Pittsburgh",destination:"Buffalo",shipmentID:"4",id:"40",currentLocation:"Alaska",price:115191,content:"Machinery",size:"14cm x 86cm x 91cm",weight:"1kg"},
    ]
  },
  {
    dateExpected: 'Sat Jun 10 2023',
    dateDelivered: 'n/a',
    dateShipped: 'Thu Apr 13 2023',
    shipmentID: '5',
    driverID: '5',
    origin: 'Pennsylvania',
    destination: 'Indiana',
    currentLocation: 'Philadelphia',
    stops: [ 'Bakersfield', 'Oklahoma', 'Bakersfield', 'Philadelphia' ],
    packages: [
      {dangerFlag:"Inspect",origin:"Wichita",destination:"Indiana",shipmentID:"5",id:"42",currentLocation:"Philadelphia",price:33927,content:"Garden Tools",size:"64cm x 56cm x 45cm",weight:"5kg"},
      {dangerFlag:"Passed",origin:"Reno",destination:"Indiana",shipmentID:"5",id:"44",currentLocation:"Philadelphia",price:179229,content:"Chemicals",size:"49cm x 29cm x 33cm",weight:"1kg"},
      {dangerFlag:"Failed",origin:"Tennessee",destination:"Indiana",shipmentID:"5",id:"43",currentLocation:"Philadelphia",price:323227,content:"Rubber",size:"81cm x 42cm x 74cm",weight:"21kg"},
      {dangerFlag:"Failed",origin:"Tennessee",destination:"Indiana",shipmentID:"5",id:"45",currentLocation:"Philadelphia",price:159804,content:"Bread",size:"108cm x 98cm x 92cm",weight:"39kg"},
      {dangerFlag:"Failed",origin:"Reno",destination:"Indiana",shipmentID:"5",id:"46",currentLocation:"Philadelphia",price:430384,content:"Rubber",size:"101cm x 89cm x 102cm",weight:"44kg"},
      {dangerFlag:"Inspect",origin:"Fort Wayne",destination:"Indiana",shipmentID:"5",id:"47",currentLocation:"Philadelphia",price:272617,content:"Metal",size:"10cm x 37cm x 44cm",weight:"35kg"},
      {dangerFlag:"Passed",origin:"Garland",destination:"Indiana",shipmentID:"5",id:"48",currentLocation:"Philadelphia",price:197906,content:"Candy",size:"73cm x 65cm x 72cm",weight:"45kg"},
      {dangerFlag:"Failed",origin:"Kansas",destination:"Indiana",shipmentID:"5",id:"49",currentLocation:"Philadelphia",price:14607,content:"Game Console",size:"61cm x 11cm x 104cm",weight:"21kg"},
      {dangerFlag:"Failed",origin:"Greensboro",destination:"Indiana",shipmentID:"5",id:"50",currentLocation:"Philadelphia",price:246490,content:"Bread",size:"55cm x 52cm x 59cm",weight:"20kg"},
      {dangerFlag:"Passed",origin:"New York",destination:"Indiana",shipmentID:"5",id:"41",currentLocation:"Philadelphia",price:90757,content:"Candy",size:"74cm x 65cm x 10cm",weight:"33kg"},
    ]
  },
  {
    dateExpected: 'Wed Jan 10 2024',
    dateDelivered: 'Mon Jan 08 2024',
    dateShipped: 'Fri Nov 24 2023',
    shipmentID: '6',
    driverID: '1',
    origin: 'Texas',
    destination: 'Lubbock',
    currentLocation: 'Lubbock',
    stops: [ 'Philadelphia', 'Buffalo', 'Lubbock' ],
    packages: [
      {dangerFlag:"Failed",origin:"Indianapolis",destination:"Lubbock",shipmentID:"6",id:"51",currentLocation:"Lubbock",price:201346,content:"Game Console",size:"40cm x 64cm x 78cm",weight:"1kg"},
      {dangerFlag:"Inspect",origin:"Indiana",destination:"Lubbock",shipmentID:"6",id:"52",currentLocation:"Lubbock",price:484615,content:"Clothing",size:"53cm x 20cm x 89cm",weight:"40kg"},
      {dangerFlag:"Passed",origin:"Tennessee",destination:"Lubbock",shipmentID:"6",id:"53",currentLocation:"Lubbock",price:60992,content:"Coffee",size:"47cm x 82cm x 61cm",weight:"3kg"},
      {dangerFlag:"Passed",origin:"Indiana",destination:"Lubbock",shipmentID:"6",id:"54",currentLocation:"Lubbock",price:5592,content:"Shoes",size:"47cm x 65cm x 90cm",weight:"4kg"},
      {dangerFlag:"Passed",origin:"Indiana",destination:"Lubbock",shipmentID:"6",id:"55",currentLocation:"Lubbock",price:38791,content:"Bread",size:"17cm x 103cm x 106cm",weight:"3kg"},
      {dangerFlag:"Passed",origin:"Indiana",destination:"Lubbock",shipmentID:"6",id:"56",currentLocation:"Lubbock",price:94341,content:"Bread",size:"29cm x 58cm x 76cm",weight:"46kg"},
      {dangerFlag:"Inspect",origin:"Texas",destination:"Lubbock",shipmentID:"6",id:"57",currentLocation:"Lubbock",price:31909,content:"Garden Tools",size:"37cm x 24cm x 55cm",weight:"39kg"},
      {dangerFlag:"Passed",origin:"Pennsylvania",destination:"Lubbock",shipmentID:"6",id:"59",currentLocation:"Lubbock",price:216968,content:"Machinery",size:"98cm x 72cm x 33cm",weight:"7kg"},
      {dangerFlag:"Failed",origin:"Wichita",destination:"Lubbock",shipmentID:"6",id:"60",currentLocation:"Lubbock",price:366420,content:"Weaves",size:"39cm x 100cm x 19cm",weight:"3kg"},
      {dangerFlag:"Passed",origin:"Reno",destination:"Lubbock",shipmentID:"6",id:"58",currentLocation:"Lubbock",price:241266,content:"Coffee",size:"108cm x 41cm x 24cm",weight:"36kg"},
    ]
  },
  {
    dateExpected: 'Thu Jul 06 2023',
    dateDelivered: 'n/a',
    dateShipped: 'Wed May 17 2023',
    shipmentID: '7',
    driverID: '2',
    origin: 'Texas',
    destination: 'Henderson',
    currentLocation: 'North Carolina',
    stops: [ 'Nevada', 'Fayette', 'North Carolina' ],
    packages: [
      {dangerFlag:"Failed",origin:"Fort Wayne",destination:"Henderson",shipmentID:"7",id:"61",currentLocation:"North Carolina",price:256252,content:"Metal",size:"98cm x 60cm x 16cm",weight:"22kg"},
      {dangerFlag:"Failed",origin:"Pittsburgh",destination:"Henderson",shipmentID:"7",id:"62",currentLocation:"North Carolina",price:368480,content:"Kitchen Utensils",size:"107cm x 106cm x 68cm",weight:"11kg"},
      {dangerFlag:"Inspect",origin:"Greensboro",destination:"Henderson",shipmentID:"7",id:"63",currentLocation:"North Carolina",price:375175,content:"Coffee",size:"47cm x 59cm x 59cm",weight:"44kg"},
      {dangerFlag:"Passed",origin:"Kansas",destination:"Henderson",shipmentID:"7",id:"64",currentLocation:"North Carolina",price:491843,content:"Shoes",size:"54cm x 37cm x 19cm",weight:"37kg"},
      {dangerFlag:"Failed",origin:"Lexington",destination:"Henderson",shipmentID:"7",id:"65",currentLocation:"North Carolina",price:89617,content:"Shoes",size:"61cm x 97cm x 88cm",weight:"4kg"},
      {dangerFlag:"Inspect",origin:"Fayette",destination:"Henderson",shipmentID:"7",id:"66",currentLocation:"North Carolina",price:318116,content:"Weaves",size:"103cm x 105cm x 57cm",weight:"19kg"},
      {dangerFlag:"Inspect",origin:"Tennessee",destination:"Henderson",shipmentID:"7",id:"68",currentLocation:"North Carolina",price:245601,content:"Bread",size:"56cm x 49cm x 24cm",weight:"27kg"},
      {dangerFlag:"Failed",origin:"Kansas",destination:"Henderson",shipmentID:"7",id:"69",currentLocation:"North Carolina",price:208754,content:"Kitchen Utensils",size:"63cm x 45cm x 99cm",weight:"24kg"},
      {dangerFlag:"Failed",origin:"Tennessee",destination:"Henderson",shipmentID:"7",id:"67",currentLocation:"North Carolina",price:108646,content:"Oranges",size:"86cm x 59cm x 24cm",weight:"0kg"},
      {dangerFlag:"Failed",origin:"Garland",destination:"Henderson",shipmentID:"7",id:"70",currentLocation:"North Carolina",price:138284,content:"Medicine",size:"21cm x 81cm x 31cm",weight:"27kg"},
    ]
  },
  {
    dateExpected: 'Tue Jun 14 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Thu Apr 21 2022',
    shipmentID: '8',
    driverID: '3',
    origin: 'Garland',
    destination: 'Indianapolis',
    currentLocation: 'Indiana',
    stops: [ 'Memphis', 'Lubbock', 'Pennsylvania', 'Indiana' ],
    packages: [
      {dangerFlag:"Passed",origin:"Nevada",destination:"Indianapolis",shipmentID:"8",id:"71",currentLocation:"Indiana",price:24242,content:"Game Console",size:"18cm x 80cm x 60cm",weight:"40kg"},
      {dangerFlag:"Passed",origin:"Arizona",destination:"Indianapolis",shipmentID:"8",id:"72",currentLocation:"Indiana",price:44293,content:"Cleaning Products",size:"58cm x 19cm x 67cm",weight:"37kg"},
      {dangerFlag:"Inspect",origin:"Ohio",destination:"Indianapolis",shipmentID:"8",id:"73",currentLocation:"Indiana",price:222038,content:"Bread",size:"12cm x 55cm x 99cm",weight:"25kg"},
      {dangerFlag:"Inspect",origin:"New York",destination:"Indianapolis",shipmentID:"8",id:"74",currentLocation:"Indiana",price:36276,content:"Weaves",size:"44cm x 50cm x 61cm",weight:"38kg"},
      {dangerFlag:"Inspect",origin:"Pennsylvania",destination:"Indianapolis",shipmentID:"8",id:"76",currentLocation:"Indiana",price:447699,content:"Garden Tools",size:"107cm x 109cm x 84cm",weight:"8kg"},
      {dangerFlag:"Failed",origin:"Philadelphia",destination:"Indianapolis",shipmentID:"8",id:"77",currentLocation:"Indiana",price:344319,content:"Coffee",size:"63cm x 19cm x 71cm",weight:"6kg"},
      {dangerFlag:"Failed",origin:"Indiana",destination:"Indianapolis",shipmentID:"8",id:"78",currentLocation:"Indiana",price:66243,content:"Cleaning Products",size:"68cm x 63cm x 13cm",weight:"23kg"},
      {dangerFlag:"Failed",origin:"Cincinnati",destination:"Indianapolis",shipmentID:"8",id:"75",currentLocation:"Indiana",price:414157,content:"Kitchen Utensils",size:"33cm x 55cm x 101cm",weight:"47kg"},
      {dangerFlag:"Inspect",origin:"Alaska",destination:"Indianapolis",shipmentID:"8",id:"80",currentLocation:"Indiana",price:131250,content:"Game Console",size:"35cm x 19cm x 98cm",weight:"41kg"},
      {dangerFlag:"Passed",origin:"Chandler",destination:"Indianapolis",shipmentID:"8",id:"79",currentLocation:"Indiana",price:260335,content:"Weaves",size:"59cm x 46cm x 79cm",weight:"23kg"},
    ]
  },
  {
    dateExpected: 'Mon Sep 19 2022',
    dateDelivered: 'Thu Sep 15 2022',
    dateShipped: 'Sat Aug 13 2022',
    shipmentID: '9',
    driverID: '4',
    origin: 'California',
    destination: 'Henderson',
    currentLocation: 'Henderson',
    stops: [ 'Nevada', 'California', 'Henderson' ],
    packages: [
      {dangerFlag:"Inspect",origin:"New York",destination:"Henderson",shipmentID:"9",id:"81",currentLocation:"Henderson",price:23359,content:"Rubber",size:"73cm x 37cm x 56cm",weight:"48kg"},
      {dangerFlag:"Failed",origin:"Chandler",destination:"Henderson",shipmentID:"9",id:"82",currentLocation:"Henderson",price:45544,content:"Clothing",size:"47cm x 63cm x 55cm",weight:"44kg"},
      {dangerFlag:"Failed",origin:"Anchorage",destination:"Henderson",shipmentID:"9",id:"83",currentLocation:"Henderson",price:362895,content:"Garden Tools",size:"54cm x 67cm x 46cm",weight:"48kg"},
      {dangerFlag:"Passed",origin:"New York",destination:"Henderson",shipmentID:"9",id:"85",currentLocation:"Henderson",price:376795,content:"Garden Tools",size:"93cm x 32cm x 74cm",weight:"34kg"},
      {dangerFlag:"Failed",origin:"Oklahoma City",destination:"Henderson",shipmentID:"9",id:"86",currentLocation:"Henderson",price:219376,content:"Rubber",size:"58cm x 60cm x 61cm",weight:"22kg"},
      {dangerFlag:"Passed",origin:"Nevada",destination:"Henderson",shipmentID:"9",id:"88",currentLocation:"Henderson",price:417444,content:"Oranges",size:"103cm x 29cm x 23cm",weight:"8kg"},
      {dangerFlag:"Passed",origin:"Lubbock",destination:"Henderson",shipmentID:"9",id:"84",currentLocation:"Henderson",price:274775,content:"Chemicals",size:"98cm x 11cm x 64cm",weight:"10kg"},
      {dangerFlag:"Passed",origin:"Pennsylvania",destination:"Henderson",shipmentID:"9",id:"87",currentLocation:"Henderson",price:84592,content:"Vehicle",size:"67cm x 96cm x 16cm",weight:"21kg"},
      {dangerFlag:"Passed",origin:"Oklahoma City",destination:"Henderson",shipmentID:"9",id:"89",currentLocation:"Henderson",price:383165,content:"Medicine",size:"109cm x 59cm x 19cm",weight:"25kg"},
      {dangerFlag:"Passed",origin:"Tennessee",destination:"Henderson",shipmentID:"9",id:"90",currentLocation:"Henderson",price:5502,content:"Oranges",size:"31cm x 55cm x 73cm",weight:"20kg"},
    ]
  },
  {
    dateExpected: 'Tue Aug 30 2022',
    dateDelivered: 'Sat Aug 27 2022',
    dateShipped: 'Sat Jul 16 2022',
    shipmentID: '10',
    driverID: '5',
    origin: 'New Orleans',
    destination: 'Tennessee',
    currentLocation: 'Tennessee',
    stops: [ 'Sacramento', 'Henderson', 'Arizona', 'Kentucky', 'Tennessee' ],
    packages: [
      {dangerFlag:"Passed",origin:"Texas",destination:"Tennessee",shipmentID:"10",id:"91",currentLocation:"Tennessee",price:129092,content:"Shoes",size:"54cm x 106cm x 46cm",weight:"48kg"},
      {dangerFlag:"Passed",origin:"Ohio",destination:"Tennessee",shipmentID:"10",id:"93",currentLocation:"Tennessee",price:484867,content:"Candy",size:"81cm x 33cm x 86cm",weight:"26kg"},
      {dangerFlag:"Passed",origin:"Fayette",destination:"Tennessee",shipmentID:"10",id:"94",currentLocation:"Tennessee",price:271099,content:"Shoes",size:"33cm x 25cm x 39cm",weight:"49kg"},
      {dangerFlag:"Failed",origin:"Nevada",destination:"Tennessee",shipmentID:"10",id:"95",currentLocation:"Tennessee",price:28247,content:"Candy",size:"47cm x 47cm x 94cm",weight:"7kg"},
      {dangerFlag:"Failed",origin:"Tennessee",destination:"Tennessee",shipmentID:"10",id:"96",currentLocation:"Tennessee",price:50701,content:"Game Console",size:"49cm x 36cm x 24cm",weight:"28kg"},
      {dangerFlag:"Inspect",origin:"Henderson",destination:"Tennessee",shipmentID:"10",id:"97",currentLocation:"Tennessee",price:120634,content:"Shoes",size:"69cm x 39cm x 45cm",weight:"40kg"},
      {dangerFlag:"Passed",origin:"Oklahoma City",destination:"Tennessee",shipmentID:"10",id:"98",currentLocation:"Tennessee",price:247704,content:"Shoes",size:"43cm x 13cm x 43cm",weight:"33kg"},
      {dangerFlag:"Failed",origin:"Bakersfield",destination:"Tennessee",shipmentID:"10",id:"99",currentLocation:"Tennessee",price:337263,content:"Clothing",size:"54cm x 35cm x 14cm",weight:"20kg"},
      {dangerFlag:"Passed",origin:"Indianapolis",destination:"Tennessee",shipmentID:"10",id:"100",currentLocation:"Tennessee",price:410823,content:"Weaves",size:"90cm x 101cm x 68cm",weight:"13kg"},
      {dangerFlag:"Inspect",origin:"Indiana",destination:"Tennessee",shipmentID:"10",id:"92",currentLocation:"Tennessee",price:365784,content:"Garden Tools",size:"57cm x 58cm x 30cm",weight:"30kg"},
    ]
  }
]