export const Shipments = [
  {
    dateExpected: 'Sat Apr 08 2023',
    dateDelivered: 'n/a',
    dateShipped: 'Fri Mar 17 2023',
    shipmentID: '1',
    driverID: '1',
    origin: 'Spain',
    destination: 'Belgium',
    tariff: 1.48,
    currentLocation: 'Saudi Arabia',
    stops: [ 'Saudi Arabia' ],
    packages: [
      {dangerFlag:"Inspect",origin:"Hungary",destination:"Belgium",shipmentID:"1",id:"1",currentLocation:"Saudi Arabia",price:134730,content:"Metal",size:"26cm x 41cm x 44cm",weight:"7kg"},
      {dangerFlag:"Failed",origin:"Finland",destination:"Belgium",shipmentID:"1",id:"2",currentLocation:"Saudi Arabia",price:132572,content:"Chemicals",size:"96cm x 14cm x 86cm",weight:"37kg"},
      {dangerFlag:"Passed",origin:"Austria",destination:"Belgium",shipmentID:"1",id:"3",currentLocation:"Saudi Arabia",price:206107,content:"Machinery",size:"40cm x 42cm x 108cm",weight:"41kg"},
      {dangerFlag:"Inspect",origin:"Sweden",destination:"Belgium",shipmentID:"1",id:"4",currentLocation:"Saudi Arabia",price:28142,content:"Machinery",size:"15cm x 83cm x 74cm",weight:"44kg"},
      {dangerFlag:"Passed",origin:"South Korea",destination:"Belgium",shipmentID:"1",id:"5",currentLocation:"Saudi Arabia",price:27853,content:"Candy",size:"16cm x 51cm x 102cm",weight:"25kg"},
      {dangerFlag:"Inspect",origin:"Austria",destination:"Belgium",shipmentID:"1",id:"6",currentLocation:"Saudi Arabia",price:194536,content:"Coffee",size:"82cm x 45cm x 85cm",weight:"27kg"},
      {dangerFlag:"Inspect",origin:"Finland",destination:"Belgium",shipmentID:"1",id:"7",currentLocation:"Saudi Arabia",price:451058,content:"Oranges",size:"18cm x 16cm x 92cm",weight:"37kg"},
      {dangerFlag:"Failed",origin:"Poland",destination:"Belgium",shipmentID:"1",id:"8",currentLocation:"Saudi Arabia",price:189549,content:"Vehicle",size:"99cm x 18cm x 83cm",weight:"4kg"},
      {dangerFlag:"Inspect",origin:"Qatar",destination:"Belgium",shipmentID:"1",id:"9",currentLocation:"Saudi Arabia",price:498699,content:"Weaves",size:"35cm x 31cm x 32cm",weight:"45kg"},
      {dangerFlag:"Inspect",origin:"Sweden",destination:"Belgium",shipmentID:"1",id:"10",currentLocation:"Saudi Arabia",price:486745,content:"Vehicle",size:"19cm x 47cm x 27cm",weight:"1kg"},

    ]
  },
  {
    dateExpected: 'Thu Jun 09 2022',
    dateDelivered: 'Wed Jun 08 2022',
    dateShipped: 'Wed May 11 2022',
    shipmentID: '2',
    driverID: '2',
    origin: 'Canada',
    destination: 'Japan',
    tariff: 2.22,
    currentLocation: 'Japan',
    stops: [ 'Bermuda', 'Italy', 'Argentina', 'Japan' ],
    packages: [
      {dangerFlag:"Passed",origin:"Qatar",destination:"Japan",shipmentID:"2",id:"11",currentLocation:"Japan",price:240828,content:"Machinery",size:"78cm x 87cm x 93cm",weight:"32kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Japan",shipmentID:"2",id:"12",currentLocation:"Japan",price:244228,content:"Medicine",size:"97cm x 77cm x 51cm",weight:"5kg"},
      {dangerFlag:"Passed",origin:"Uruguay",destination:"Japan",shipmentID:"2",id:"13",currentLocation:"Japan",price:59153,content:"Chemicals",size:"11cm x 10cm x 94cm",weight:"39kg"},
      {dangerFlag:"Passed",origin:"Sweden",destination:"Japan",shipmentID:"2",id:"14",currentLocation:"Japan",price:106611,content:"Shoes",size:"95cm x 88cm x 45cm",weight:"6kg"},
      {dangerFlag:"Failed",origin:"Finland",destination:"Japan",shipmentID:"2",id:"15",currentLocation:"Japan",price:222296,content:"Coffee",size:"53cm x 80cm x 67cm",weight:"41kg"},
      {dangerFlag:"Passed",origin:"French Polynesia",destination:"Japan",shipmentID:"2",id:"16",currentLocation:"Japan",price:168053,content:"Candy",size:"15cm x 37cm x 21cm",weight:"17kg"},
      {dangerFlag:"Passed",origin:"Qatar",destination:"Japan",shipmentID:"2",id:"19",currentLocation:"Japan",price:451848,content:"Garden Tools",size:"93cm x 78cm x 89cm",weight:"10kg"},
      {dangerFlag:"Passed",origin:"Hungary",destination:"Japan",shipmentID:"2",id:"17",currentLocation:"Japan",price:198516,content:"Oranges",size:"15cm x 102cm x 32cm",weight:"32kg"},
      {dangerFlag:"Failed",origin:"South Korea",destination:"Japan",shipmentID:"2",id:"18",currentLocation:"Japan",price:317597,content:"Coffee",size:"76cm x 31cm x 30cm",weight:"48kg"},
      {dangerFlag:"Passed",origin:"Italy",destination:"Japan",shipmentID:"2",id:"20",currentLocation:"Japan",price:377931,content:"Metal",size:"24cm x 35cm x 77cm",weight:"10kg"},
      
    ]
  },
  {
    dateExpected: 'Thu Mar 24 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Mon Feb 14 2022',
    shipmentID: '3',
    driverID: '3',
    origin: 'France',
    destination: 'Belgium',
    tariff: 1.48,
    currentLocation: 'Canada',
    stops: [ 'Canada' ],
    packages: [
      {dangerFlag:"Inspect",origin:"Ireland",destination:"Belgium",shipmentID:"3",id:"21",currentLocation:"Canada",price:95421,content:"Machinery",size:"105cm x 99cm x 15cm",weight:"30kg"},
      {dangerFlag:"Failed",origin:"Finland",destination:"Belgium",shipmentID:"3",id:"22",currentLocation:"Canada",price:79103,content:"Weaves",size:"51cm x 62cm x 42cm",weight:"34kg"},
      {dangerFlag:"Passed",origin:"Australia",destination:"Belgium",shipmentID:"3",id:"23",currentLocation:"Canada",price:330254,content:"Candy",size:"61cm x 18cm x 20cm",weight:"46kg"},
      {dangerFlag:"Passed",origin:"Austria",destination:"Belgium",shipmentID:"3",id:"24",currentLocation:"Canada",price:216659,content:"Metal",size:"25cm x 56cm x 43cm",weight:"41kg"},
      {dangerFlag:"Passed",origin:"Sweden",destination:"Belgium",shipmentID:"3",id:"25",currentLocation:"Canada",price:19022,content:"Chemicals",size:"90cm x 66cm x 67cm",weight:"26kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Belgium",shipmentID:"3",id:"26",currentLocation:"Canada",price:131839,content:"Machinery",size:"56cm x 64cm x 61cm",weight:"43kg"},
      {dangerFlag:"Failed",origin:"United States",destination:"Belgium",shipmentID:"3",id:"27",currentLocation:"Canada",price:468569,content:"Metal",size:"80cm x 28cm x 81cm",weight:"16kg"},
      {dangerFlag:"Passed",origin:"UAE",destination:"Belgium",shipmentID:"3",id:"28",currentLocation:"Canada",price:166416,content:"Chemicals",size:"68cm x 24cm x 66cm",weight:"23kg"},
      {dangerFlag:"Inspect",origin:"Sweden",destination:"Belgium",shipmentID:"3",id:"29",currentLocation:"Canada",price:331214,content:"Cleaning Products",size:"26cm x 17cm x 81cm",weight:"26kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Belgium",shipmentID:"3",id:"30",currentLocation:"Canada",price:26029,content:"Bath Products",size:"85cm x 103cm x 60cm",weight:"30kg"},
      
    ]
  },
  {
    dateExpected: 'Mon Apr 03 2023',
    dateDelivered: 'n/a',
    dateShipped: 'Mon Mar 13 2023',
    shipmentID: '4',
    driverID: '4',
    origin: 'Netherlands',
    destination: 'Uruguay',
    tariff: 5.29,
    currentLocation: 'Ireland',
    stops: [
      'Netherlands',
      'United States',
      'Uruguay',
      'Argentina',
      'Ireland'
    ],
    packages:[
      {dangerFlag:"Failed",origin:"Netherlands",destination:"Uruguay",shipmentID:"4",id:"31",currentLocation:"Ireland",price:74224,content:"Vehicle",size:"103cm x 98cm x 61cm",weight:"25kg"},
      {dangerFlag:"Failed",origin:"Qatar",destination:"Uruguay",shipmentID:"4",id:"32",currentLocation:"Ireland",price:363960,content:"Chemicals",size:"12cm x 55cm x 50cm",weight:"39kg"},
      {dangerFlag:"Passed",origin:"Canada",destination:"Uruguay",shipmentID:"4",id:"33",currentLocation:"Ireland",price:274389,content:"Weaves",size:"64cm x 81cm x 101cm",weight:"20kg"},
      {dangerFlag:"Failed",origin:"Qatar",destination:"Uruguay",shipmentID:"4",id:"35",currentLocation:"Ireland",price:212091,content:"Game Console",size:"106cm x 90cm x 66cm",weight:"46kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Uruguay",shipmentID:"4",id:"34",currentLocation:"Ireland",price:185650,content:"Coffee",size:"35cm x 46cm x 46cm",weight:"12kg"},
      {dangerFlag:"Failed",origin:"Hungary",destination:"Uruguay",shipmentID:"4",id:"36",currentLocation:"Ireland",price:343735,content:"Garden Tools",size:"10cm x 105cm x 53cm",weight:"38kg"},
      {dangerFlag:"Failed",origin:"Finland",destination:"Uruguay",shipmentID:"4",id:"38",currentLocation:"Ireland",price:288361,content:"Bread",size:"86cm x 29cm x 100cm",weight:"17kg"},
      {dangerFlag:"Inspect",origin:"Canada",destination:"Uruguay",shipmentID:"4",id:"37",currentLocation:"Ireland",price:481590,content:"Metal",size:"95cm x 94cm x 23cm",weight:"0kg"},
      {dangerFlag:"Passed",origin:"Hungary",destination:"Uruguay",shipmentID:"4",id:"39",currentLocation:"Ireland",price:354337,content:"Medicine",size:"46cm x 18cm x 37cm",weight:"48kg"},
      {dangerFlag:"Inspect",origin:"Japan",destination:"Uruguay",shipmentID:"4",id:"40",currentLocation:"Ireland",price:387246,content:"Cleaning Products",size:"63cm x 30cm x 72cm",weight:"23kg"},
      
    ]
  },
  {
    dateExpected: 'Mon Apr 18 2022',
    dateDelivered: 'Sun Apr 17 2022',
    dateShipped: 'Fri Mar 25 2022',
    shipmentID: '5',
    driverID: '5',
    origin: 'Greece',
    destination: 'Argentina',
    tariff: 6.88,
    currentLocation: 'Argentina',
    stops: [ 'Sweden', 'Argentina' ],
    packages:[
      {dangerFlag:"Inspect",origin:"Finland",destination:"Argentina",shipmentID:"5",id:"41",currentLocation:"Argentina",price:322607,content:"Clothing",size:"47cm x 104cm x 41cm",weight:"20kg"},
      {dangerFlag:"Passed",origin:"Belgium",destination:"Argentina",shipmentID:"5",id:"42",currentLocation:"Argentina",price:291337,content:"Metal",size:"64cm x 35cm x 22cm",weight:"43kg"},
      {dangerFlag:"Failed",origin:"Italy",destination:"Argentina",shipmentID:"5",id:"44",currentLocation:"Argentina",price:303656,content:"Machinery",size:"16cm x 69cm x 87cm",weight:"23kg"},
      {dangerFlag:"Failed",origin:"South Korea",destination:"Argentina",shipmentID:"5",id:"43",currentLocation:"Argentina",price:489456,content:"Chemicals",size:"49cm x 107cm x 12cm",weight:"22kg"},
      {dangerFlag:"Passed",origin:"UAE",destination:"Argentina",shipmentID:"5",id:"45",currentLocation:"Argentina",price:285765,content:"Coffee",size:"43cm x 33cm x 63cm",weight:"18kg"},
      {dangerFlag:"Failed",origin:"Qatar",destination:"Argentina",shipmentID:"5",id:"46",currentLocation:"Argentina",price:412409,content:"Candy",size:"55cm x 79cm x 40cm",weight:"36kg"},
      {dangerFlag:"Passed",origin:"Netherlands",destination:"Argentina",shipmentID:"5",id:"48",currentLocation:"Argentina",price:19919,content:"Weaves",size:"52cm x 18cm x 31cm",weight:"12kg"},
      {dangerFlag:"Passed",origin:"Austria",destination:"Argentina",shipmentID:"5",id:"49",currentLocation:"Argentina",price:296735,content:"Garden Tools",size:"99cm x 78cm x 25cm",weight:"8kg"},
      {dangerFlag:"Inspect",origin:"Saudi Arabia",destination:"Argentina",shipmentID:"5",id:"47",currentLocation:"Argentina",price:72314,content:"Bath Products",size:"41cm x 91cm x 56cm",weight:"12kg"},
      {dangerFlag:"Inspect",origin:"Netherlands",destination:"Argentina",shipmentID:"5",id:"50",currentLocation:"Argentina",price:198050,content:"Clothing",size:"18cm x 50cm x 22cm",weight:"31kg"},
      
    ]
  },
  {
    dateExpected: 'Wed Feb 22 2023',
    dateDelivered: 'Mon Feb 20 2023',
    dateShipped: 'Mon Jan 02 2023',
    shipmentID: '6',
    driverID: '1',
    origin: 'Sweden',
    destination: 'South Korea',
    tariff: 5.48,
    currentLocation: 'South Korea',
    stops: [ 'Panama', 'Argentina', 'South Korea' ],
    packages: [
      {dangerFlag:"Passed",origin:"France",destination:"South Korea",shipmentID:"6",id:"51",currentLocation:"South Korea",price:409606,content:"Weaves",size:"106cm x 12cm x 26cm",weight:"36kg"},
      {dangerFlag:"Failed",origin:"Poland",destination:"South Korea",shipmentID:"6",id:"52",currentLocation:"South Korea",price:433690,content:"Rubber",size:"22cm x 73cm x 50cm",weight:"40kg"},
      {dangerFlag:"Passed",origin:"Uruguay",destination:"South Korea",shipmentID:"6",id:"53",currentLocation:"South Korea",price:335986,content:"Machinery",size:"57cm x 97cm x 88cm",weight:"47kg"},
      {dangerFlag:"Passed",origin:"Netherlands",destination:"South Korea",shipmentID:"6",id:"56",currentLocation:"South Korea",price:55177,content:"Vehicle",size:"20cm x 25cm x 52cm",weight:"13kg"},
      {dangerFlag:"Passed",origin:"Spain",destination:"South Korea",shipmentID:"6",id:"54",currentLocation:"South Korea",price:96298,content:"Chemicals",size:"51cm x 54cm x 107cm",weight:"24kg"},
      {dangerFlag:"Passed",origin:"Canada",destination:"South Korea",shipmentID:"6",id:"55",currentLocation:"South Korea",price:149220,content:"Rubber",size:"43cm x 26cm x 56cm",weight:"9kg"},
      {dangerFlag:"Passed",origin:"United States",destination:"South Korea",shipmentID:"6",id:"58",currentLocation:"South Korea",price:224125,content:"Game Console",size:"69cm x 80cm x 45cm",weight:"23kg"},
      {dangerFlag:"Failed",origin:"Bermuda",destination:"South Korea",shipmentID:"6",id:"57",currentLocation:"South Korea",price:257417,content:"Kitchen Utensils",size:"101cm x 48cm x 29cm",weight:"30kg"},
      {dangerFlag:"Failed",origin:"Argentina",destination:"South Korea",shipmentID:"6",id:"60",currentLocation:"South Korea",price:367591,content:"Game Console",size:"76cm x 72cm x 22cm",weight:"28kg"},
      {dangerFlag:"Passed",origin:"Saudi Arabia",destination:"South Korea",shipmentID:"6",id:"59",currentLocation:"South Korea",price:328745,content:"Garden Tools",size:"13cm x 31cm x 100cm",weight:"16kg"},
      
    ]
  },
  {
    dateExpected: 'Mon Aug 15 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Fri Aug 05 2022',
    shipmentID: '7',
    driverID: '2',
    origin: 'Netherlands',
    destination: 'Argentina',
    tariff: 6.88,
    currentLocation: 'South Korea',
    stops: [ 'Uruguay', 'South Korea' ],
    packages: [
      {dangerFlag:"Inspect",origin:"Uruguay",destination:"Argentina",shipmentID:"7",id:"61",currentLocation:"South Korea",price:202163,content:"Oranges",size:"97cm x 75cm x 54cm",weight:"44kg"},
      {dangerFlag:"Failed",origin:"UAE",destination:"Argentina",shipmentID:"7",id:"62",currentLocation:"South Korea",price:356870,content:"Bath Products",size:"97cm x 60cm x 22cm",weight:"47kg"},
      {dangerFlag:"Passed",origin:"Panama",destination:"Argentina",shipmentID:"7",id:"63",currentLocation:"South Korea",price:173699,content:"Vehicle",size:"21cm x 78cm x 91cm",weight:"7kg"},
      {dangerFlag:"Failed",origin:"Argentina",destination:"Argentina",shipmentID:"7",id:"64",currentLocation:"South Korea",price:106572,content:"Clothing",size:"97cm x 39cm x 51cm",weight:"49kg"},
      {dangerFlag:"Passed",origin:"Poland",destination:"Argentina",shipmentID:"7",id:"65",currentLocation:"South Korea",price:232473,content:"Medicine",size:"19cm x 34cm x 46cm",weight:"14kg"},
      {dangerFlag:"Passed",origin:"Finland",destination:"Argentina",shipmentID:"7",id:"66",currentLocation:"South Korea",price:405791,content:"Machinery",size:"77cm x 66cm x 67cm",weight:"36kg"},
      {dangerFlag:"Passed",origin:"French Polynesia",destination:"Argentina",shipmentID:"7",id:"67",currentLocation:"South Korea",price:333078,content:"Metal",size:"60cm x 88cm x 37cm",weight:"43kg"},
      {dangerFlag:"Passed",origin:"Italy",destination:"Argentina",shipmentID:"7",id:"68",currentLocation:"South Korea",price:416994,content:"Chemicals",size:"54cm x 68cm x 11cm",weight:"38kg"},
      {dangerFlag:"Passed",origin:"Greece",destination:"Argentina",shipmentID:"7",id:"69",currentLocation:"South Korea",price:276068,content:"Weaves",size:"56cm x 44cm x 107cm",weight:"21kg"},
      {dangerFlag:"Failed",origin:"Czech Republic",destination:"Argentina",shipmentID:"7",id:"70",currentLocation:"South Korea",price:496694,content:"Rubber",size:"68cm x 29cm x 52cm",weight:"7kg"},

    ]
  },
  {
    dateExpected: 'Sun Apr 17 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Tue Mar 15 2022',
    shipmentID: '8',
    driverID: '3',
    origin: 'Saudi Arabia',
    destination: 'UAE',
    tariff: 3.28,
    currentLocation: 'Belgium',
    stops: [ 'Spain', 'Belgium' ],
    packages: [
      {dangerFlag:"Passed",origin:"Finland",destination:"UAE",shipmentID:"8",id:"72",currentLocation:"Belgium",price:57842,content:"Cleaning Products",size:"57cm x 96cm x 70cm",weight:"42kg"},
      {dangerFlag:"Inspect",origin:"Greece",destination:"UAE",shipmentID:"8",id:"71",currentLocation:"Belgium",price:230031,content:"Rubber",size:"51cm x 31cm x 21cm",weight:"24kg"},
      {dangerFlag:"Failed",origin:"Netherlands",destination:"UAE",shipmentID:"8",id:"73",currentLocation:"Belgium",price:291353,content:"Rubber",size:"60cm x 43cm x 32cm",weight:"34kg"},
      {dangerFlag:"Failed",origin:"Uruguay",destination:"UAE",shipmentID:"8",id:"74",currentLocation:"Belgium",price:159595,content:"Machinery",size:"52cm x 42cm x 95cm",weight:"27kg"},
      {dangerFlag:"Inspect",origin:"Poland",destination:"UAE",shipmentID:"8",id:"75",currentLocation:"Belgium",price:5565,content:"Kitchen Utensils",size:"72cm x 27cm x 61cm",weight:"46kg"},
      {dangerFlag:"Inspect",origin:"Ireland",destination:"UAE",shipmentID:"8",id:"76",currentLocation:"Belgium",price:323125,content:"Garden Tools",size:"66cm x 67cm x 20cm",weight:"43kg"},
      {dangerFlag:"Passed",origin:"South Korea",destination:"UAE",shipmentID:"8",id:"77",currentLocation:"Belgium",price:284398,content:"Shoes",size:"40cm x 101cm x 98cm",weight:"47kg"},
      {dangerFlag:"Failed",origin:"Netherlands",destination:"UAE",shipmentID:"8",id:"78",currentLocation:"Belgium",price:160787,content:"Clothing",size:"10cm x 100cm x 84cm",weight:"12kg"},
      {dangerFlag:"Passed",origin:"Qatar",destination:"UAE",shipmentID:"8",id:"79",currentLocation:"Belgium",price:54467,content:"Cleaning Products",size:"34cm x 29cm x 94cm",weight:"6kg"},
      {dangerFlag:"Inspect",origin:"Czech Republic",destination:"UAE",shipmentID:"8",id:"80",currentLocation:"Belgium",price:158456,content:"Cleaning Products",size:"79cm x 59cm x 62cm",weight:"14kg"},
      
    ]
  },
  {
    dateExpected: 'Mon Mar 28 2022',
    dateDelivered: 'Thu Mar 24 2022',
    dateShipped: 'Thu Mar 10 2022',
    shipmentID: '9',
    driverID: '4',
    origin: 'Bermuda',
    destination: 'Ireland',
    tariff: 1.48,
    currentLocation: 'Ireland',
    stops: [ 'France', 'Ireland' ],
    packages: [
      {dangerFlag:"Failed",origin:"United States",destination:"Ireland",shipmentID:"9",id:"81",currentLocation:"Ireland",price:403709,content:"Shoes",size:"85cm x 18cm x 81cm",weight:"9kg"},
      {dangerFlag:"Failed",origin:"Argentina",destination:"Ireland",shipmentID:"9",id:"82",currentLocation:"Ireland",price:320895,content:"Game Console",size:"59cm x 27cm x 86cm",weight:"10kg"},
      {dangerFlag:"Passed",origin:"Panama",destination:"Ireland",shipmentID:"9",id:"83",currentLocation:"Ireland",price:227149,content:"Garden Tools",size:"55cm x 81cm x 76cm",weight:"4kg"},
      {dangerFlag:"Failed",origin:"France",destination:"Ireland",shipmentID:"9",id:"84",currentLocation:"Ireland",price:399705,content:"Rubber",size:"84cm x 52cm x 100cm",weight:"32kg"},
      {dangerFlag:"Passed",origin:"Saudi Arabia",destination:"Ireland",shipmentID:"9",id:"85",currentLocation:"Ireland",price:62822,content:"Weaves",size:"24cm x 30cm x 45cm",weight:"14kg"},
      {dangerFlag:"Failed",origin:"Australia",destination:"Ireland",shipmentID:"9",id:"87",currentLocation:"Ireland",price:130621,content:"Vehicle",size:"108cm x 67cm x 61cm",weight:"30kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Ireland",shipmentID:"9",id:"86",currentLocation:"Ireland",price:158218,content:"Coffee",size:"58cm x 14cm x 11cm",weight:"33kg"},
      {dangerFlag:"Inspect",origin:"UAE",destination:"Ireland",shipmentID:"9",id:"88",currentLocation:"Ireland",price:146004,content:"Kitchen Utensils",size:"49cm x 90cm x 46cm",weight:"5kg"},
      {dangerFlag:"Passed",origin:"Greece",destination:"Ireland",shipmentID:"9",id:"89",currentLocation:"Ireland",price:362936,content:"Garden Tools",size:"20cm x 74cm x 50cm",weight:"26kg"},
      {dangerFlag:"Passed",origin:"Ireland",destination:"Ireland",shipmentID:"9",id:"90",currentLocation:"Ireland",price:12462,content:"Clothing",size:"74cm x 27cm x 98cm",weight:"44kg"},

    ]
  },
  {
    dateExpected: 'Fri Feb 18 2022',
    dateDelivered: 'n/a',
    dateShipped: 'Mon Feb 07 2022',
    shipmentID: '10',
    driverID: '5',
    origin: 'French Polynesia',
    destination: 'Hungary',
    tariff: 1.48,
    currentLocation: 'Ireland',
    stops: [ 'Qatar', 'Hungary', 'Ireland' ],
    packages: [
      {dangerFlag:"Passed",origin:"Hungary",destination:"Hungary",shipmentID:"10",id:"91",currentLocation:"Ireland",price:155473,content:"Chemicals",size:"39cm x 34cm x 100cm",weight:"45kg"},
      {dangerFlag:"Passed",origin:"Poland",destination:"Hungary",shipmentID:"10",id:"92",currentLocation:"Ireland",price:11876,content:"Cleaning Products",size:"16cm x 17cm x 89cm",weight:"41kg"},
      {dangerFlag:"Passed",origin:"Finland",destination:"Hungary",shipmentID:"10",id:"94",currentLocation:"Ireland",price:217863,content:"Candy",size:"91cm x 90cm x 70cm",weight:"31kg"},
      {dangerFlag:"Failed",origin:"Finland",destination:"Hungary",shipmentID:"10",id:"93",currentLocation:"Ireland",price:121550,content:"Metal",size:"48cm x 78cm x 24cm",weight:"1kg"},
      {dangerFlag:"Passed",origin:"UAE",destination:"Hungary",shipmentID:"10",id:"95",currentLocation:"Ireland",price:129292,content:"Oranges",size:"47cm x 51cm x 78cm",weight:"2kg"},
      {dangerFlag:"Passed",origin:"United States",destination:"Hungary",shipmentID:"10",id:"96",currentLocation:"Ireland",price:243933,content:"Shoes",size:"58cm x 101cm x 57cm",weight:"44kg"},
      {dangerFlag:"Passed",origin:"Hungary",destination:"Hungary",shipmentID:"10",id:"98",currentLocation:"Ireland",price:326427,content:"Medicine",size:"109cm x 89cm x 64cm",weight:"44kg"},
      {dangerFlag:"Inspect",origin:"Italy",destination:"Hungary",shipmentID:"10",id:"97",currentLocation:"Ireland",price:102418,content:"Vehicle",size:"26cm x 108cm x 31cm",weight:"18kg"},
      {dangerFlag:"Passed",origin:"Finland",destination:"Hungary",shipmentID:"10",id:"99",currentLocation:"Ireland",price:25640,content:"Garden Tools",size:"107cm x 42cm x 93cm",weight:"15kg"},
      {dangerFlag:"Failed",origin:"Saudi Arabia",destination:"Hungary",shipmentID:"10",id:"100",currentLocation:"Ireland",price:39463,content:"Cleaning Products",size:"45cm x 12cm x 45cm",weight:"10kg"},

    ]
  }
]
